
services:
  db: # This is the name of our service (you can call it anything, but 'db' is common)
    image: postgres:15 # Specifies the Docker image to use. 'postgres:15' means PostgreSQL version 15.
    restart: always # Ensures the container restarts automatically if it stops (e.g., after a system reboot)
    environment: # Environment variables for the PostgreSQL container
      POSTGRES_DB: pulse_ipo_db # The name of the database that will be created
      POSTGRES_USER: ${DATABASE_USER} # The username for connecting to the database
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} # The password for the database user
    ports:
      # Maps a port on your host machine to a port inside the container.
      # Format: "HOST_PORT:CONTAINER_PORT"
      # PostgreSQL's default port is 5432.
      # If 5432 is already in use on your machine, you can change the host port (e.g., "5433:5432")
      - "5432:5432"
    volumes:
      # This is crucial for data persistence.
      # It maps a named Docker volume ('db-data') to the PostgreSQL data directory inside the container.
      # This means your database data will not be lost if you stop or remove the container.
      - db-data:/var/lib/postgresql/data

# Defines the named volume used above. Docker will manage this volume.
volumes:
  db-data:
